[package]
name = "papi"
version = "0.2.0"
authors = ["Yang Keao <keao.yang@yahoo.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
libpapi_sys = { version = "0.2.0", path = "./libpapi_sys" }

[dev-dependencies]
clap = "2.33"
nix = "0.18.0"
libc = "0.2"
